### ISSUE TITLE
Add all the InterMines to FAIRsharing.org

### ISSUE THREAD

**Issue by yochannah** [intermine/outreach#3]
[FAIRsharing.org](http://www.FAIRsharing.org): "A curated, informative and educational resource on data and metadata standards, inter-related to databases and data policies."

After a chat with @drosophilic, it looks like the easiest plan is to do as follows.

1. Bulk export all the InterMines from the [registry](http://registry.intermine.org/service/instances)
2. Add contact details for all the mines. We have twitter handles for some already.
3. Pass on to @drosophilic to create the entries and chase down the owners (or pass it on to us if the owners can't be contacted) - this allows them to keep things nice and uniform between fairsharing entries.

**Comment by justinccdev** [comment]
Hi @yochannah. Registering new InterMine instances with fairsharing.org is one of our items for the FAIR InterMine grant, if you weren't aware.  Either we can push data to @Drosophilic as you describe and/or we could embed Bioschemas DataCatalog entries on a registry webpage somewhere so that fairsharing.org can gather that periodically directly (or even via a third-party crawler).

**Comment by yochannah** [comment]
Hah - if I was aware, I'd probably forgotten. @Drosophilic any preferences?

**Comment by yochannah** [comment]
(both might also be an option?)

**Comment by Drosophilic** [comment]
Hi all, 
Marking up in bioschemas would be great, but in the meantime you could just push the data to FAIRsharing and we'll generate records that you can then review and claim.

**Comment by yochannah** [comment]
This is complete! <3 Thanks to all the awesome FAIRSharing folks
