### ISSUE TITLE
Publications about InterMine & Publications that cite InterMine - tell us about them!

### ISSUE THREAD

**Issue by yochannah** [intermine/outreach#7]
Have you published something recently that either cited InterMine or was about your own InterMine (or both?)

Leave a comment with the link and we'll help spread the word and add it to our list!

**Comment by julie-sullivan** [comment]
Were we going to use a tool to aggregate these papers?

**Comment by yochannah** [comment]
@tnabtaf uses Zotero for Galaxy I think, but I haven't had a chance to look into it or set it up for InterMine. 

Some recent papers are curated here: https://twitter.com/search?q=%23imcite

**Comment by rachellyne** [comment]
I use pubcrawler to scan pubmed and Mendeley to organise papers.  I have used pubcrawler for years so there may be something better.

**Comment by tnabtaf** [comment]
Hi All,

I just migrated the Galaxy Library from CiteULike to Zotero.  I quite liked CiteULike, but it's not getting much maintenance and more and more journal web pages were failing to automatically load in CiteULike.

And, now, I quite like Zotero too.  Since moving in September I've only had to paste bibtex for 1 of 200+ papers.  The only error I have found so far that's easy to make in Zotero is adding duplicate entries (Zotero also makes them easy to detect.

I looked Mendeley as well as Zotero.  I think both are good choices. I went with Zotero because people in the Galaxy community are already using it for other purposes.  Zotero is also open, if that matters to you.

I've got email alerts set up with Google Scholar, Web of Science, Wiley, ScienceDirect, and PubMed.  I then have custom code that 

* Merges all those email alerts into a coherent whole
* Tracks what pubs I have already looked at and/or added to the library
* Produces an HTML page that helps me curate the new papers.

I curate papers every two weeks.  In an average two week period I'll look at ~100 papers and add ~60 to the library.  If you only get alerts from one source, or if you get less than 20 alters a month, then then using/custom code to manage them is probably not worth the effort.

Links:

* [Galaxy Pub Library home](https://www.zotero.org/groups/1732893/galaxy)
* [Galaxy Pub Library Pubs](https://www.zotero.org/groups/1732893/galaxy/items)
* [About the pub library](https://galaxyproject.org/publication-library/)
* [The First 5000 pubs blog post](https://galaxyproject.org/blog/2017-10-5000-pubs/)
* [The custom code](https://github.com/tnabtaf/pub_spork)

**Comment by tnabtaf** [comment]
By the way, the PubMed searches I use only search the abstracts (which is all pubmed has most of the time, isn't it?). This misses probably 90% of Galaxy papers.  Google Scholar returns the most hits, but is also limited on the length of the search string, which means (for me) a fair number of false positives too.

**Comment by rachellyne** [comment]
I have the same with InterMine - my pubcrawler doesn't tent to pick up InterMine cited papers - so I tend to resort to manual!  I get loads of alerts and regularly check the pubmed cited links.

**Comment by tnabtaf** [comment]
Let me know if there is interest in using the custom code (https://github.com/tnabtaf/pub_spork) to manage InterMine's alerts and citations.  That's just the motivation I would need to write a **Getting Started** doc.
